<?php

namespace Database\Seeders;

use App\Models\Tarifa;
use Illuminate\Database\Seeder;

class TarifasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tarifas = [
            // Tarifas regulares de día (8 registros)
            [
                'nombre' => 'Tarifa Básica - Medellín Centro',
                'descripcion' => 'Tarifa estándar para servicios dentro del centro de Medellín',
                'tipo' => 'basica',
                'tarifa_base' => 8000.00,
                'valor_por_km' => 2500.00,
                'valor_por_minuto' => 150.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles']),
                'horario_inicio' => '06:00:00',
                'horario_fin' => '20:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes']),
                'multiplicador_festivos' => 1.2,
                'activa' => true,
                'precio_minimo' => 12000.00,
                'precio_maximo' => 150000.00,
                'tipo_servicio' => 'economico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa más económica para servicios urbanos',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Premium - Servicios Ejecutivos',
                'descripcion' => 'Tarifa para servicios ejecutivos y empresariales',
                'tipo' => 'premium',
                'tarifa_base' => 15000.00,
                'valor_por_km' => 3500.00,
                'valor_por_minuto' => 250.00,
                'zona_cobertura' => json_encode(['poblado', 'envigado', 'sabaneta', 'itagui']),
                'horario_inicio' => '05:00:00',
                'horario_fin' => '23:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado']),
                'multiplicador_festivos' => 1.3,
                'activa' => true,
                'precio_minimo' => 20000.00,
                'precio_maximo' => 300000.00,
                'tipo_servicio' => 'premium',
                'categoria_vehiculo' => 'suv',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Servicio premium con vehículos de alta gama',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Nocturna - Medellín',
                'descripcion' => 'Tarifa especial para servicios nocturnos y madrugada',
                'tipo' => 'nocturna',
                'tarifa_base' => 12000.00,
                'valor_por_km' => 3000.00,
                'valor_por_minuto' => 200.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'bello', 'copacabana']),
                'horario_inicio' => '20:00:00',
                'horario_fin' => '06:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.4,
                'activa' => true,
                'precio_minimo' => 15000.00,
                'precio_maximo' => 200000.00,
                'tipo_servicio' => 'economico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa nocturna con recargo por horario',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Fin de Semana',
                'descripcion' => 'Tarifa especial para sábados y domingos',
                'tipo' => 'weekend',
                'tarifa_base' => 10000.00,
                'valor_por_km' => 2800.00,
                'valor_por_minuto' => 180.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'envigado']),
                'horario_inicio' => '06:00:00',
                'horario_fin' => '22:00:00',
                'dias_semana' => json_encode(['sabado', 'domingo']),
                'multiplicador_festivos' => 1.25,
                'activa' => true,
                'precio_minimo' => 14000.00,
                'precio_maximo' => 180000.00,
                'tipo_servicio' => 'economico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa competitiva para fines de semana',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Aeropuerto José María Córdova',
                'descripcion' => 'Tarifa especial para servicios desde/hacia el aeropuerto',
                'tipo' => 'aeropuerto',
                'tarifa_base' => 25000.00,
                'valor_por_km' => 2000.00,
                'valor_por_minuto' => 0.00,
                'zona_cobertura' => json_encode(['rionegro', 'medelin_aeropuerto']),
                'horario_inicio' => '00:00:00',
                'horario_fin' => '23:59:59',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.15,
                'activa' => true,
                'precio_minimo' => 80000.00,
                'precio_maximo' => 120000.00,
                'tipo_servicio' => 'aeropuerto',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa fija aeropuerto con recargo de peajes incluido',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Corporativa - Empresas',
                'descripcion' => 'Tarifa especial para clientes corporativos con descuentos',
                'tipo' => 'corporativa',
                'tarifa_base' => 7000.00,
                'valor_por_km' => 2200.00,
                'valor_por_minuto' => 120.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'sabaneta', 'envigado', 'bello']),
                'horario_inicio' => '05:00:00',
                'horario_fin' => '22:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes']),
                'multiplicador_festivos' => 1.1,
                'activa' => true,
                'precio_minimo' => 10000.00,
                'precio_maximo' => 200000.00,
                'tipo_servicio' => 'corporativo',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa preferencial para empresas con contrato',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Express - Servicios Rápidos',
                'descripcion' => 'Tarifa para servicios express y entregas rápidas',
                'tipo' => 'express',
                'tarifa_base' => 6000.00,
                'valor_por_km' => 2000.00,
                'valor_por_minuto' => 100.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles']),
                'horario_inicio' => '07:00:00',
                'horario_fin' => '19:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado']),
                'multiplicador_festivos' => 1.0,
                'activa' => true,
                'precio_minimo' => 8000.00,
                'precio_maximo' => 50000.00,
                'tipo_servicio' => 'express',
                'categoria_vehiculo' => 'moto',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => false,
                'observaciones' => 'Servicio rápido para distancias cortas y entregas',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa VIP - Lujo y Confort',
                'descripcion' => 'Tarifa premium para servicios de lujo con vehículos exclusivos',
                'tipo' => 'vip',
                'tarifa_base' => 30000.00,
                'valor_por_km' => 5000.00,
                'valor_por_minuto' => 400.00,
                'zona_cobertura' => json_encode(['poblado', 'envigado', 'sabaneta']),
                'horario_inicio' => '00:00:00',
                'horario_fin' => '23:59:59',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.5,
                'activa' => true,
                'precio_minimo' => 50000.00,
                'precio_maximo' => 500000.00,
                'tipo_servicio' => 'vip',
                'categoria_vehiculo' => 'lujo',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Servicio VIP con vehículos de lujo y conductores especializados',
                'creado_por' => 1
            ],

            // Tarifas especiales y promocionales (12 registros)
            [
                'nombre' => 'Tarifa Estudiantes - Universidad',
                'descripcion' => 'Tarifa con descuento para estudiantes universitarios',
                'tipo' => 'estudiante',
                'tarifa_base' => 6500.00,
                'valor_por_km' => 2000.00,
                'valor_por_minuto' => 120.00,
                'zona_cobertura' => json_encode(['laureles', 'universidad', 'estadio']),
                'horario_inicio' => '06:00:00',
                'horario_fin' => '22:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes']),
                'multiplicador_festivos' => 1.0,
                'activa' => true,
                'precio_minimo' => 8000.00,
                'precio_maximo' => 80000.00,
                'tipo_servicio' => 'economico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Descuento del 15% para estudiantes con carné vigente',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Tercera Edad',
                'descripcion' => 'Tarifa preferencial para adultos mayores de 65 años',
                'tipo' => 'tercera_edad',
                'tarifa_base' => 7000.00,
                'valor_por_km' => 2200.00,
                'valor_por_minuto' => 130.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'bello']),
                'horario_inicio' => '07:00:00',
                'horario_fin' => '18:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes']),
                'multiplicador_festivos' => 1.0,
                'activa' => true,
                'precio_minimo' => 9000.00,
                'precio_maximo' => 100000.00,
                'tipo_servicio' => 'economico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Descuento del 10% para mayores de 65 años',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Médica - Urgencias',
                'descripcion' => 'Tarifa especial para servicios médicos y urgencias',
                'tipo' => 'medica',
                'tarifa_base' => 10000.00,
                'valor_por_km' => 2800.00,
                'valor_por_minuto' => 200.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'bello', 'envigado', 'itagui']),
                'horario_inicio' => '00:00:00',
                'horario_fin' => '23:59:59',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.2,
                'activa' => true,
                'precio_minimo' => 12000.00,
                'precio_maximo' => 150000.00,
                'tipo_servicio' => 'medico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Prioridad alta para servicios médicos y hospitalarios',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Turística - City Tour',
                'descripcion' => 'Tarifa especial para turistas y recorridos por la ciudad',
                'tipo' => 'turistica',
                'tarifa_base' => 20000.00,
                'valor_por_km' => 1500.00,
                'valor_por_minuto' => 300.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'guatape', 'piedra_del_penol']),
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'dias_semana' => json_encode(['sabado', 'domingo']),
                'multiplicador_festivos' => 1.3,
                'activa' => true,
                'precio_minimo' => 80000.00,
                'precio_maximo' => 400000.00,
                'tipo_servicio' => 'turistico',
                'categoria_vehiculo' => 'suv',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Incluye guía turística y paradas en sitios de interés',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Zona Rosa - Entretenimiento',
                'descripcion' => 'Tarifa para la zona de entretenimiento nocturno',
                'tipo' => 'zona_rosa',
                'tarifa_base' => 9000.00,
                'valor_por_km' => 2600.00,
                'valor_por_minuto' => 180.00,
                'zona_cobertura' => json_encode(['poblado', 'zona_rosa', 'provenza']),
                'horario_inicio' => '18:00:00',
                'horario_fin' => '04:00:00',
                'dias_semana' => json_encode(['jueves', 'viernes', 'sabado']),
                'multiplicador_festivos' => 1.4,
                'activa' => true,
                'precio_minimo' => 12000.00,
                'precio_maximo' => 100000.00,
                'tipo_servicio' => 'nocturno',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Servicio especializado para zona de rumba',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Compartido - Carpooling',
                'descripcion' => 'Tarifa reducida para servicios compartidos',
                'tipo' => 'compartido',
                'tarifa_base' => 4000.00,
                'valor_por_km' => 1500.00,
                'valor_por_minuto' => 80.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles']),
                'horario_inicio' => '06:00:00',
                'horario_fin' => '22:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes']),
                'multiplicador_festivos' => 1.0,
                'activa' => true,
                'precio_minimo' => 5000.00,
                'precio_maximo' => 40000.00,
                'tipo_servicio' => 'compartido',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => false,
                'observaciones' => 'Servicio económico compartido con otros pasajeros',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Evento Especial',
                'descripcion' => 'Tarifa para eventos masivos y conciertos',
                'tipo' => 'evento',
                'tarifa_base' => 15000.00,
                'valor_por_km' => 3000.00,
                'valor_por_minuto' => 250.00,
                'zona_cobertura' => json_encode(['atanasio_girardot', 'teatro_pablo_tobon', 'plaza_mayor']),
                'horario_inicio' => '17:00:00',
                'horario_fin' => '02:00:00',
                'dias_semana' => json_encode(['viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.6,
                'activa' => false,
                'precio_minimo' => 20000.00,
                'precio_maximo' => 200000.00,
                'tipo_servicio' => 'evento',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Se activa solo durante eventos masivos programados',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Madrugada - 24 Horas',
                'descripcion' => 'Tarifa especial para servicios de madrugada',
                'tipo' => 'madrugada',
                'tarifa_base' => 14000.00,
                'valor_por_km' => 3200.00,
                'valor_por_minuto' => 220.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'bello']),
                'horario_inicio' => '01:00:00',
                'horario_fin' => '05:00:00',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.5,
                'activa' => true,
                'precio_minimo' => 18000.00,
                'precio_maximo' => 180000.00,
                'tipo_servicio' => 'nocturno',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa especial con recargo por horario de madrugada',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Lluvia - Clima Adverso',
                'descripcion' => 'Tarifa con recargo para días de lluvia intensa',
                'tipo' => 'lluvia',
                'tarifa_base' => 10000.00,
                'valor_por_km' => 2800.00,
                'valor_por_minuto' => 200.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'bello', 'envigado']),
                'horario_inicio' => '00:00:00',
                'horario_fin' => '23:59:59',
                'dias_semana' => json_encode(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.3,
                'activa' => false,
                'precio_minimo' => 14000.00,
                'precio_maximo' => 160000.00,
                'tipo_servicio' => 'economico',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Se activa automáticamente con alerta meteorológica',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Día de la Madre',
                'descripcion' => 'Tarifa promocional especial para el Día de la Madre',
                'tipo' => 'promocional',
                'tarifa_base' => 7000.00,
                'valor_por_km' => 2300.00,
                'valor_por_minuto' => 140.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'envigado', 'sabaneta']),
                'horario_inicio' => '08:00:00',
                'horario_fin' => '20:00:00',
                'dias_semana' => json_encode(['domingo']),
                'multiplicador_festivos' => 0.9,
                'activa' => false,
                'precio_minimo' => 10000.00,
                'precio_maximo' => 120000.00,
                'tipo_servicio' => 'promocional',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Descuento especial del 10% para el Día de la Madre',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Black Friday',
                'descripcion' => 'Tarifa promocional para el Black Friday',
                'tipo' => 'promocional',
                'tarifa_base' => 6000.00,
                'valor_por_km' => 2000.00,
                'valor_por_minuto' => 120.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'premium_plaza', 'santafe']),
                'horario_inicio' => '06:00:00',
                'horario_fin' => '23:00:00',
                'dias_semana' => json_encode(['viernes']),
                'multiplicador_festivos' => 0.8,
                'activa' => false,
                'precio_minimo' => 8000.00,
                'precio_maximo' => 100000.00,
                'tipo_servicio' => 'promocional',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => false,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Descuento del 20% para viajes a centros comerciales',
                'creado_por' => 1
            ],
            [
                'nombre' => 'Tarifa Navideña',
                'descripcion' => 'Tarifa especial para temporada navideña',
                'tipo' => 'navidad',
                'tarifa_base' => 12000.00,
                'valor_por_km' => 3000.00,
                'valor_por_minuto' => 200.00,
                'zona_cobertura' => json_encode(['centro', 'poblado', 'laureles', 'alumbrados_navidenos']),
                'horario_inicio' => '17:00:00',
                'horario_fin' => '01:00:00',
                'dias_semana' => json_encode(['viernes', 'sabado', 'domingo']),
                'multiplicador_festivos' => 1.4,
                'activa' => false,
                'precio_minimo' => 15000.00,
                'precio_maximo' => 200000.00,
                'tipo_servicio' => 'festivo',
                'categoria_vehiculo' => 'sedan',
                'aplica_recargo_aeropuerto' => true,
                'aplica_recargo_peaje' => true,
                'observaciones' => 'Tarifa especial para disfrutar los alumbrados navideños',
                'creado_por' => 1
            ]
        ];

        foreach ($tarifas as $tarifa) {
            Tarifa::updateOrCreate(
                ['nombre' => $tarifa['nombre']],
                array_merge($tarifa, [
                    'actualizado_por' => 1,
                ])
            );
        }
    }
}
