<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiculosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vehiculos')->insert([
            [
                'placa' => 'ABC123',
                'marca' => 'Honda',
                'modelo' => 'CB125F',
                'color' => 'Rojo',
                'ano' => 2020,
                'cilindraje' => 125,
                'numero_motor' => 'MOT001ABC123',
                'numero_chasis' => 'CHA001ABC123',
                'propietario_nombre' => 'Pedro Jimenez',
                'propietario_cedula' => '10203040',
                'propietario_telefono' => '3145678901',
                'seguro_numero' => 'SEG001',
                'seguro_vigencia' => '2025-12-31',
                'soat_numero' => 'SOAT001',
                'soat_vigencia' => '2025-06-30',
                'tecnicomecanica_numero' => 'TEC001',
                'tecnicomecanica_vigencia' => '2025-03-15',
                'tarjeta_propiedad' => 'PROP001',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'XYZ789',
                'marca' => 'Yamaha',
                'modelo' => 'XTZ125',
                'color' => 'Azul',
                'ano' => 2019,
                'cilindraje' => 125,
                'numero_motor' => 'MOT002XYZ789',
                'numero_chasis' => 'CHA002XYZ789',
                'propietario_nombre' => 'Carmen Lopez',
                'propietario_cedula' => '50607080',
                'propietario_telefono' => '3167890123',
                'seguro_numero' => 'SEG002',
                'seguro_vigencia' => '2025-11-20',
                'soat_numero' => 'SOAT002',
                'soat_vigencia' => '2025-07-22',
                'tecnicomecanica_numero' => 'TEC002',
                'tecnicomecanica_vigencia' => '2025-04-10',
                'tarjeta_propiedad' => 'PROP002',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'DEF456',
                'marca' => 'Suzuki',
                'modelo' => 'AX100',
                'color' => 'Negro',
                'ano' => 2021,
                'cilindraje' => 100,
                'numero_motor' => 'MOT003DEF456',
                'numero_chasis' => 'CHA003DEF456',
                'propietario_nombre' => 'Miguel Torres',
                'propietario_cedula' => '90102030',
                'propietario_telefono' => '3189012345',
                'seguro_numero' => 'SEG003',
                'seguro_vigencia' => '2026-01-15',
                'soat_numero' => 'SOAT003',
                'soat_vigencia' => '2025-08-30',
                'tecnicomecanica_numero' => 'TEC003',
                'tecnicomecanica_vigencia' => '2025-05-25',
                'tarjeta_propiedad' => 'PROP003',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'GHI012',
                'marca' => 'Honda',
                'modelo' => 'XR150L',
                'color' => 'Verde',
                'ano' => 2018,
                'cilindraje' => 150,
                'numero_motor' => 'MOT004GHI012',
                'numero_chasis' => 'CHA004GHI012',
                'propietario_nombre' => 'Rosa Martinez',
                'propietario_cedula' => '40506070',
                'propietario_telefono' => '3134567890',
                'seguro_numero' => 'SEG004',
                'seguro_vigencia' => '2025-10-10',
                'soat_numero' => 'SOAT004',
                'soat_vigencia' => '2025-05-15',
                'tecnicomecanica_numero' => 'TEC004',
                'tecnicomecanica_vigencia' => '2025-02-20',
                'tarjeta_propiedad' => 'PROP004',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'JKL345',
                'marca' => 'Yamaha',
                'modelo' => 'FZ-FI',
                'color' => 'Blanco',
                'ano' => 2020,
                'cilindraje' => 150,
                'numero_motor' => 'MOT005JKL345',
                'numero_chasis' => 'CHA005JKL345',
                'propietario_nombre' => 'Diego Vargas',
                'propietario_cedula' => '80901020',
                'propietario_telefono' => '3198765432',
                'seguro_numero' => 'SEG005',
                'seguro_vigencia' => '2026-02-28',
                'soat_numero' => 'SOAT005',
                'soat_vigencia' => '2025-09-12',
                'tecnicomecanica_numero' => 'TEC005',
                'tecnicomecanica_vigencia' => '2025-06-08',
                'tarjeta_propiedad' => 'PROP005',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'MNO678',
                'marca' => 'Honda',
                'modelo' => 'CB110',
                'color' => 'Gris',
                'ano' => 2019,
                'cilindraje' => 110,
                'numero_motor' => 'MOT006MNO678',
                'numero_chasis' => 'CHA006MNO678',
                'propietario_nombre' => 'Ana Gomez',
                'propietario_cedula' => '12345678',
                'propietario_telefono' => '3112233445',
                'seguro_numero' => 'SEG006',
                'seguro_vigencia' => '2025-11-15',
                'soat_numero' => 'SOAT006',
                'soat_vigencia' => '2025-12-20',
                'tecnicomecanica_numero' => 'TEC006',
                'tecnicomecanica_vigencia' => '2025-08-12',
                'tarjeta_propiedad' => 'PROP006',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'PQR901',
                'marca' => 'Suzuki',
                'modelo' => 'DR200',
                'color' => 'Amarillo',
                'ano' => 2021,
                'cilindraje' => 200,
                'numero_motor' => 'MOT007PQR901',
                'numero_chasis' => 'CHA007PQR901',
                'propietario_nombre' => 'Carlos Herrera',
                'propietario_cedula' => '23456789',
                'propietario_telefono' => '3123344556',
                'seguro_numero' => 'SEG007',
                'seguro_vigencia' => '2026-03-10',
                'soat_numero' => 'SOAT007',
                'soat_vigencia' => '2026-01-05',
                'tecnicomecanica_numero' => 'TEC007',
                'tecnicomecanica_vigencia' => '2025-09-18',
                'tarjeta_propiedad' => 'PROP007',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'STU234',
                'marca' => 'Yamaha',
                'modelo' => 'Crypton',
                'color' => 'Morado',
                'ano' => 2020,
                'cilindraje' => 110,
                'numero_motor' => 'MOT008STU234',
                'numero_chasis' => 'CHA008STU234',
                'propietario_nombre' => 'Lucia Morales',
                'propietario_cedula' => '34567890',
                'propietario_telefono' => '3134455667',
                'seguro_numero' => 'SEG008',
                'seguro_vigencia' => '2025-12-05',
                'soat_numero' => 'SOAT008',
                'soat_vigencia' => '2025-10-30',
                'tecnicomecanica_numero' => 'TEC008',
                'tecnicomecanica_vigencia' => '2025-07-25',
                'tarjeta_propiedad' => 'PROP008',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'VWX567',
                'marca' => 'Honda',
                'modelo' => 'Wave110',
                'color' => 'Azul Claro',
                'ano' => 2018,
                'cilindraje' => 110,
                'numero_motor' => 'MOT009VWX567',
                'numero_chasis' => 'CHA009VWX567',
                'propietario_nombre' => 'Roberto Silva',
                'propietario_cedula' => '45678901',
                'propietario_telefono' => '3145566778',
                'seguro_numero' => 'SEG009',
                'seguro_vigencia' => '2025-09-22',
                'soat_numero' => 'SOAT009',
                'soat_vigencia' => '2025-11-18',
                'tecnicomecanica_numero' => 'TEC009',
                'tecnicomecanica_vigencia' => '2025-06-30',
                'tarjeta_propiedad' => 'PROP009',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'YZA890',
                'marca' => 'Suzuki',
                'modelo' => 'EN125',
                'color' => 'Naranja',
                'ano' => 2022,
                'cilindraje' => 125,
                'numero_motor' => 'MOT010YZA890',
                'numero_chasis' => 'CHA010YZA890',
                'propietario_nombre' => 'Patricia Ruiz',
                'propietario_cedula' => '56789012',
                'propietario_telefono' => '3156677889',
                'seguro_numero' => 'SEG010',
                'seguro_vigencia' => '2026-04-15',
                'soat_numero' => 'SOAT010',
                'soat_vigencia' => '2026-02-10',
                'tecnicomecanica_numero' => 'TEC010',
                'tecnicomecanica_vigencia' => '2025-10-08',
                'tarjeta_propiedad' => 'PROP010',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'BCD123',
                'marca' => 'Honda',
                'modelo' => 'XR190L',
                'color' => 'Rojo Metalizado',
                'ano' => 2021,
                'cilindraje' => 190,
                'numero_motor' => 'MOT011BCD123',
                'numero_chasis' => 'CHA011BCD123',
                'propietario_nombre' => 'Fernando Castro',
                'propietario_cedula' => '67890123',
                'propietario_telefono' => '3167788990',
                'seguro_numero' => 'SEG011',
                'seguro_vigencia' => '2026-01-20',
                'soat_numero' => 'SOAT011',
                'soat_vigencia' => '2025-12-15',
                'tecnicomecanica_numero' => 'TEC011',
                'tecnicomecanica_vigencia' => '2025-09-05',
                'tarjeta_propiedad' => 'PROP011',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'EFG456',
                'marca' => 'Yamaha',
                'modelo' => 'TTR125',
                'color' => 'Verde Militar',
                'ano' => 2019,
                'cilindraje' => 125,
                'numero_motor' => 'MOT012EFG456',
                'numero_chasis' => 'CHA012EFG456',
                'propietario_nombre' => 'Sandra Lopez',
                'propietario_cedula' => '78901234',
                'propietario_telefono' => '3178899001',
                'seguro_numero' => 'SEG012',
                'seguro_vigencia' => '2025-08-30',
                'soat_numero' => 'SOAT012',
                'soat_vigencia' => '2025-07-08',
                'tecnicomecanica_numero' => 'TEC012',
                'tecnicomecanica_vigencia' => '2025-04-22',
                'tarjeta_propiedad' => 'PROP012',
                'estado' => 'mantenimiento',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'HIJ789',
                'marca' => 'Suzuki',
                'modelo' => 'GN125',
                'color' => 'Plateado',
                'ano' => 2020,
                'cilindraje' => 125,
                'numero_motor' => 'MOT013HIJ789',
                'numero_chasis' => 'CHA013HIJ789',
                'propietario_nombre' => 'Mario Vega',
                'propietario_cedula' => '89012345',
                'propietario_telefono' => '3189900112',
                'seguro_numero' => 'SEG013',
                'seguro_vigencia' => '2025-11-08',
                'soat_numero' => 'SOAT013',
                'soat_vigencia' => '2025-09-25',
                'tecnicomecanica_numero' => 'TEC013',
                'tecnicomecanica_vigencia' => '2025-05-15',
                'tarjeta_propiedad' => 'PROP013',
                'estado' => 'activo',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
